# Generated by Django 4.0.3 on 2022-03-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_lodging_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.CharField(default='fun times 2.0', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='price',
            field=models.CharField(default='3.7', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lodging',
            name='max_occupants',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lodging',
            name='price',
            field=models.IntegerField(default='3'),
            preserve_default=False,
        ),
    ]
