# Generated by Django 4.0.3 on 2022-03-14 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_friendrequest_friendlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.friendlist')),
                ('possible_friends', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.friendrequest')),
                ('trips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.trip')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
