# Generated by Django 4.0.3 on 2022-03-15 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_profile_friend_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friend_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.friendlist'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='possible_friends',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.friendrequest'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='trips',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.trip'),
        ),
    ]
