# Generated by Django 4.0.3 on 2022-03-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.IntegerField(),
        ),
    ]
