# Generated by Django 4.0.3 on 2022-03-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_activity_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
